baseURL = 'https://xzl01.github.io/'
languageCode = 'zh-cn'
title = "HarryLoong's Blog"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[markup]
  [markup.highlight]
    noClasses = false
    style = "github-dark"
  [markup.goldmark.renderer]
    unsafe = true
